# .github/workflows/python-app.yml
name: Build Python application

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest  # Use a Windows runner

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify the Python version you want to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from requirements.txt

    - name: Build executable
      run: |
        .\build.bat  # Run the batch file to build the executable

    - name: Upload executable
      uses: actions/upload-artifact@v2
      with:
        name: autoclicker-executable
        path: dist/autoclicker.exe  # Path to the built executable
